# Generated by Django 5.1.1 on 2024-09-30 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_enrollment_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
